---
title: "Maps and Charts"
author: "Charles Jason Tinant"
creation date: "5/9/2018"
last update: "5/13/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# token for NOAA API tied to jtinant@olc.edu
options(noaakey = "VpcuARumMpCfFyclKHPfvskEYnaiLJHD")
# see 'rnoaa' for details
# Get API key (aka, token) at http://www.ncdc.noaa.gov/cdo-web/token
```

```{r setup, include=FALSE}
# sets the path and what to do with chunks----
knitr::opts_chunk$set(echo = TRUE)
#opts_chunk$set(fig.width=10,
#               fig.height=7,
#               out.width = "600px",
#               out.height = "420px",
#               fig.path = "lecture_figs/making-maps-")
```

```{r library}
# Sets up the library of packages 
library("maps") # outlines of continents, countries, states & counties 
library("mapdata") # higher-resolution outlines
library('ggmap')
library("RColorBrewer")
library("tidyverse")
library("rio") # more robust I/O - to import and clean data
library("dataRetrieval") # USGS data import
library("rnoaa")
library("here")

library("workflowr") # creates a research website
library("colorspace")
# Packages that are not likely to be called
# library("DiagrammeR") # used to call 'mermaid' for a Gantt chart
# library("thesisdown") # used to knit a thesis follows bookdown
# library("bookdown") # 
# library(knitr) # not sure if this needs to be loaded??
# library(DataExplorer)

# rio suggests:
# install_formats() # use once.  installs suggested packages for 'rio'
# GREA provides an RStudio add-in to import data using rio.
```

```{r map_points, eval=FALSE}
# Creates points for maps. No need to evaluate.  
# The output files have been created.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 'station' is a variable for NOAA weather station locations
# 'gage' is a variable for USGS stream gages
# 'site' is a variable for OST monitoring stations

# 'station' 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# get station id with the mapping tool at 
# https://www.ncdc.noaa.gov/cdo-web/datatools/findstation
# iterate across a list of station ids by purrr::map 
# to get NOAA station meta data using rnoaa::ncdc_stations
# the output is a list of 7 x 2 x 9.
# flatten into a dataframe by purrr::flatten 
# reorder and rename columns by dplyr
# save the station df by rio
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sta_input <- data.frame(name = c('RAPID CITY RGNL AP', 
                                 'HOT SPRINGS', 
                                'OELRICHS', 
                                'INTERIOR 3 NE', 
                                'COTTONWOOD 2 E', 
                                'LONG VALLEY',
                                'HARRISON',
                                'AINSWORTH, NE'),
                        id = c("GHCND:USW00024090", 
                               "GHCND:US1SDFR0001",
                               "GHCND:USC00396212",
                               "GHCND:USC00394184",
                               "GHCND:USC00391972",
                               "GHCND:USC00394983",
                               "GHCND:USC00253615",
                               "GHCND:USC00250050"),
                        stringsAsFactors = FALSE)

station <- map(sta_input$id, ncdc_stations)
station <- flatten_dfr(station)

station <- station %>%
  rename(lat = latitude) %>%
  rename(lon = longitude) %>%
  select(id, name, lat, lon, everything())

export(station, "data/station_meta.csv")

# 'gage' 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# get gage ids by USGS watermapper
# iterate across a list of gage ids by purrr::map_dfr 
# to get gage metadata using dataRetrieval::readNWISsite
# reorder and rename columns by dplyr
# save the station df by rio
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

gage_id <- data.frame(name = c("WHITE R NR NE-SD STATE LINE", 
                              "WHITE R NEAR OGLALA SD", 
                              "WHITE CLAY CR NEAR OGLALA SD", 
                              "WHITE R NEAR INTERIOR SD", 
                              "WOUNDED KNEE CREEK AT WOUNDED KNEE SD",
                              "BEAR IN THE LODGE CR NEAR WANBLEE SD", 
                              "WHITE R NEAR KADOKA SD", 
                              "BLACK PIPE CREEK NR BELVIDERE SD", 
                              "LITTLE WHITE R NEAR MARTIN SD", 
                              "LAKE CR BELOW REFUGE NEAR TUTHILL SD", 
                              "LITTLE WHITE R NEAR VETAL SD", 
                              "SOUTH FORK BAD R NEAR COTTONWOOD SD", 
                              "BAD R NEAR MIDLAND SD"),
                     id = c('06445685', '06446000', '06445980', 
                            '06446500', '06446100', '06446700', 
                            '06447000', '06447230', '06447500', 
                            '06449000',  '06449100', '06440200',
                            '06441000'),
                     stringsAsFactors = FALSE)
# CHECK: long valley end date

gage <- map_dfr(gage_id$id, readNWISsite) 
gage <- gage %>%
  select(site_no, station_nm, dec_lat_va, dec_long_va, everything())
export(gage, "data/gage_meta.csv")
```

```{r projectAreaMap}
# import point data
station <- import("data/station_meta.csv")
gage <- import("data/gage_meta.csv")

# import polygon data
counties <- map_data("county") 
counties <- subset(counties, region %in% 
   c("south dakota", "nebraska"))
prr <- subset(counties, subregion %in% 
   c("shannon", "jackson", "bennett"))

# download a basemap from Google Maps
map_base <- ggmap::get_googlemap(center = c(lon = mean(gage$dec_long_va), 
lat = mean(gage$dec_lat_va)), zoom = 8, size = c(640, 640), 
style = c(feature = "terrain", element = "labels", 
          visibility = "off"), legend = "bottom")

# plot points on top of basemap
ggmap::ggmap(map_base) +
ggplot2::geom_point(ggplot2::aes(x = lon, y = lat),
data = station, alpha = 1.0, size = 3, shape = 5, color = "red") +
ggplot2::geom_point(ggplot2::aes(x = dec_long_va, y = dec_lat_va),
data = gage, alpha = 1.0, size = 2, shape = 15, color = "blue") +
ggplot2::geom_polygon(data = prr, 
              aes(x = long, y = lat, group = group), 
              color = "black", fill = "NA")


library("maps")
# library("mapdata") # need to install
library("ggmap")
library("ggplot2")

# map of south dakota and nebraska----

# subset region using data from the 'maps' package
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sd_neb <- map_data("state")
sd_neb <- subset(sd_neb, region %in% 
   c("south dakota", "nebraska"))



ggplot() + 
  geom_polygon(data = counties, 
              aes(x = long, y = lat, group = group), 
              color = "gray", fill = NA) +
  geom_polygon(data = sd_neb, 
              aes(x = long, y = lat, group = group), 
              color = "black", fill = NA) +  
  geom_polygon(data = prr, 
              aes(x = long, y = lat, group = group), 
              color = "black", fill = "red") +
  coord_fixed(1.3) +
  ggtitle("Pine Ridge Reservation", 
          subtitle = "Oglala Lakota, Jackson and Bennett Counties") +
  xlab("") +
  ylab("") +
  theme_minimal()
#map_full <- 
#print(map_full)

#ggmap(sq_map2) + 
#      geom_point(data = sisquoc, color = "red", size = 4) +
#      geom_text(data = sisquoc, aes(label = paste("  ", 
#      as.character(name), sep = "")), angle = 60, hjust = 0, 
#      color = "yellow")

#map2disk <-ggplot2::ggsave(filename="c.png", plot=map2disp, width=6, height=6, units = "in")

```

```{r map-tutorial}
# I think this is to set for bookdown?
#title: Making Maps With R
#author: "Eric C. Anderson"
#output:
#  html_document:
#    toc: yes
#  bookdown::html_chapter:
#    toc: no
#layout: default_with_disqus

# Making Maps with R {#map-making-in-R} 
# https://raw.githubusercontent.com/eriqande/rep-res-course/master/lectures/making-maps-with-R.rmd

## Intro {#map-making-intro}
# old package ->  `maps` package for making simple outlines
# of maps and plotting lat-long points and paths on them.

# New packages -> `sp`, `rgdal`, and `rgeos` functionality of 
# traditional GIS packages (like ArcGIS, etc).  *Not covered*
  
# Middle way -> `ggmap` to tile detailed base maps from Google Earth 
# or Open Street Maps, upon which spatial data may be plotted.
# all the power of ggplot.  Goes out to different map servers and
# grabs base maps to plot things on, then it sets up the coordinate 
# system and writes it out as the base layer for further ggplotting.  
# *but does not support different projections*

# some standard map packages.
#install.packages(c("maps", "mapdata"))
#devtools::install_github("dkahle/ggmap")

# You need to translate the `maps` data into a data frame format for 
# `ggplot`.  `ggplot2` provides the `map_data()` function. 

# Syntax: `map_data("name")` where "name" is a quoted string of the 
# name of a map in the `maps` or `mapdata` package.

# Data Structure for ggplot & maps
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# `long` is longitude.  W of prime meridian = negative
# `lat` is latitude.
# `order` gives order that `ggplot` should "connect the dots"
# `region` and `subregion` tell what region or subregion a set of 
#    points surrounds.
# `group`  *Very_important!*  Controls whether adjacent points should 
#    be connected by lines.  Members of the same group get connected.
#    "having points in diff. groups means `ggplot` "lifts the pen" 

# A simple US map
# ~~~~~~~~~~~~~~~
# Plot using `geom_polygon()` draw lines between points & "close them 
#    up" (i.e. draws a line from the last point back to the 1st point)
# Map the `group` aesthetic to the `group` column
#    `x = long` and `y = lat` are the other aesthetics.
# 'coord_fixed(x)' is important when drawing maps to fix the relationship 
#    between one unit in the $y$ direction and one unit in the 
#    $x$ direction. If you change the window size or the size of the 
#    pdf file then the _aspect ratio_ remains unchanged.
#    the 'x' above is by visual inspection
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# gg1 <- map_data("usa") # prepare data as data frame for ggplot
# ggplot() + 
# geom_polygon(data = usa, aes(x=long, y = lat, group = group)) + 
# fill = NA, color = "red") + 
# coord_fixed(1.3)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Adding points to the map
# ~~~~~~~~~~~~~~~~~~~~~~~~
# To add black and yellow points to the map

# labs <- data.frame(
#   long = c(-122.064873, -122.306417),
#   lat = c(36.951968, 47.644855),
#   names = c("SWFSC-FED", "NWFSC"),
#   stringsAsFactors = FALSE
# )  
#
# gg1 + 
#   geom_point(data = labs, aes(x = long, y = lat), 
#   color = "black", size = 5) +
#   geom_point(data = labs, aes(x = long, y = lat), 
#   color = "yellow", size = 4)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# State maps
# ~~~~~~~~~~
# states <- map_data("state")
# dim(states)
# head(states)
# tail(states)

# Plot all the states, all colored a little differently
# As above, but map fill to `region` and state border lines are white
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ggplot(data = states) + 
#  geom_polygon(aes(x = long, y = lat, fill = region, group = group),
#               color = "white") + 
#  coord_fixed(1.3) +
#  guides(fill=FALSE)  # do this to leave off the color legend

# Plot a subset of states with the `subset` command
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# west_coast <- subset(states, region %in% 
#   c("california", "oregon", # "washington"))
#    
# ggplot(data = west_coast) + 
#   geom_polygon(aes(x = long, y = lat, group = group), 
#     fill = "palegreen", color = "black") +
# coord_fixed(1.3)

#### Zoom in on California and look at counties
# ca_df <- subset(states, region == "california")
#    head(ca_df)

# Now, let's also get the county lines there
 #   counties <- map_data("county")
 #   ca_county <- subset(counties, region == "california")

 #   head(ca_county)

# Plot the state first 
# but let's ditch the axes gridlines, and gray background by
# using the super-wonderful `theme_nothing()`.

#    ca_base <- ggplot(data = ca_df, mapping = aes(x = long, y = lat, 
# group = group)) + 
#      coord_fixed(1.3) + 
 #     geom_polygon(color = "black", fill = "gray")
#    ca_base + theme_nothing()

# Now plot the county boundaries in white:
#
#    ca_base + theme_nothing() + 
#      geom_polygon(data = ca_county, fill = NA, color = "white") +
# get the state border back on top
#      geom_polygon(color = "black", fill = NA)  
```

```{r ggmap}
## ggmap {#ggmap-hooray}----

# The `ggmap` package is the most exciting R mapping tool in a long 
# time!  You might be able to get better looking maps at some 
# resolutions by using shapefiles and rasters from 
# naturalearthdata.com
# but `ggmap` will get you 95% of the way there with only 5% of the 
# work!

### How ggmap works

# ggmap simplifies the process of downloading base maps from Google or 
# Open Street Maps or Stamen Maps to use in the background of your 
# plots. It also sets the axis scales, etc, in a nice way.  
# Once you have gotten your maps, you make a call with `ggmap()` much 
# as you would with `ggplot()`
# Let's do by example.

### Sisquoctober
# Here is a small data frame of points from the Sisquoc River.
sisquoc <- read.table("data/sisquoc-points.txt", sep = "\t", header = TRUE)
# notes: ggmap tends to use "lon" instead of "long" for longitude.

# make a bounding box
# ~~~~~~~~~~~~~~~~~~~
# `ggmap` typically asks you for a zoom level, 
# But we can try using `ggmap`'s `make_bbox` function to make a boun

sbbox <- make_bbox(lon = sisquoc$lon, lat = sisquoc$lat, f = .1)

# Now, when we grab the map ggmap will try to fit it into that 
# bounding box by first getting the map. 
# By default it gets it from Google.  I want it to be a satellite map

# Wrong way!
# ~~~~~~~~~~
# sq_map <- get_map(location = sbbox, maptype = "satellite", 
#                  source = "google")
# ggmap(sq_map) + geom_point(data = sisquoc, 
#                          mapping = aes(x = lon, y = lat), 
#                           color = "red")

# Nope! That was a fail, but we got a warning about it too. 
# (Actually it is a little better than before because I hacked `ggmap` 
# a bit...) 

# Using the zoom level in ggmap 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  Zoom levels go from 3 (world scale to 20 (house scale)).
#    compute the mean lat and lon

# ggmap-satelite
ll_means <- sapply(sisquoc[2:3], mean)

sq_map2 <- get_map(location = ll_means,  maptype = "satellite", source = "google", zoom = 15)

ggmap(sq_map2) + 
      geom_point(data = sisquoc, color = "red", size = 4) +
      geom_text(data = sisquoc, aes(label = paste("  ", 
      as.character(name), sep = "")), angle = 60, hjust = 0, 
      color = "yellow")


# ggmap-terrain
# Use the "terrain" type of ggmap - with bad lettering

sq_map3 <- get_map(location = ll_means,  
                   maptype = "terrain", source = "google", 
                   zoom = 15)
ggmap(sq_map3) + 
      geom_point(data = sisquoc, color = "red", size = 4) +
      geom_text(data = sisquoc, 
                aes(label = paste("  ", as.character(name), 
                                  sep = "")), angle = 60, 
                hjust = 0, color = "yellow")

#  ggmap-gps
# plot a gps route----
# Map elevation to the color of the path using rainbow colors.

# The right zoom and position for the map is trial and error.  
# Go to Google maps to figure out where the center should be (right click and choose "What's here?" to get the lat-long of any point. )
# The `make_bbox` function has never really worked for me.
bike <- read.csv("data/bike-ride.csv")

bikemap1 <- get_map(location = c(-122.080954, 36.971709), 
                    maptype = "terrain", source = "google", zoom = 14)

ggmap(bikemap1) + 
      geom_path(data = bike, aes(color = elevation), size = 3, 
                lineend = "round") + 
      scale_color_gradientn(colours = rainbow(7), 
                            breaks = seq(25, 200, by = 25))
    

# fish-sampling
### Fish sampling locations
# Example - coded wire tag data base to georeferenced marine locations 

# I did all that you can check out 
# [this](https://github.com/eriqande/pbt-feasibility/blob/4ea2fc960f74f66b5ec3a11c107cdc52bfb346dc/Rmd/02-02-explore-recovery-and-catch-sample-data.Rmd#looking-at-locations-of-location-codes)

# The data are hierarchically structured.  Author is interested in how 
# close together sites in the same "region" or "area" or "sector" are, 
# and pondering whether it is OK to aggregate fish recoveries at a 
# certain level for the purposes of getting a better overall estimate 
# of the proportion of fish from different hatcheries in these areas.

# So, pretty simple stuff.  I just want to plot these points on a map, 
# and paint them a different color according to their sector, region, 
# area, etc.

# bc <- readRDS("data/bc_sites.rds")

# look at some wide georeferenced data (1,113 observations)
# bc %>% select(state_or_province:sub_location, longitude, latitude)

# Enumerate using `dplyr`:
# bc %>% 
# group_by(sector, region, area) %>%
# tally()

# That looks good.  It appears like we could probably color code over 
# the whole area down to region, and then down to area within 
# subregions.

#### Makin' a map.

# Let us try again to use `make_bbox()` to see if it will work better 
# when used on a large scale.

# compute the bounding box
bc_bbox <- make_bbox(lat = latitude, lon = longitude, data = bc)
bc_bbox

# grab the maps from google
bc_big <- get_map(location = bc_bbox, source = "google", 
                  maptype = "terrain")

# * Cool! That was about as easy as could be.  North is in the north, 
# south is in the south, and  the three reddish points are clearly 
# aberrant ones at the mouths of rivers.

# Plot the points and color them by sector
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ggmap(bc_big) + 
  geom_point(data = bc, mapping = aes(x = longitude, y = latitude, 
                                      color = sector))


# r ggmap-coloring
#### Coloring it by region

# We should be able to color these all by region to some extent 
# (it might get overwhelming), but let us have a go with it.
# Notice that region names are unique overall (not just within N or S) so we can just color by region name.

ggmap(bc_big) + 
  geom_point(data = bc, mapping = aes(x = longitude, y = latitude, color = region))

# Once again that was dirt easy, though at this scale with all the different regions, it is hard to resolve all the colors.


# ggmap-zoom-in
#### Zooming in on each region and coloring by area

# Use a function to make a series of maps: one for each region, in 
# which the areas in that region are colored differently.
# Approach: you pass it the region and it makes the plot.

region_plot <- function(MyRegion) {
  tmp <- bc %>% filter(region == MyRegion)
  bbox <- make_bbox(lon = longitude, lat = latitude, data = tmp)
  mymap <- get_map(location = bbox, source = "google", 
                   maptype = "terrain")
  
# now we want to count up how many areas there are
NumAreas <- tmp %>% summarise(n_distinct(area))
NumPoints <- nrow(tmp)
  
the_map <- ggmap(mymap) +
    geom_point(data = tmp, mapping = aes(x = longitude, y = latitude), 
               size = 4, color = "black") +
    geom_point(data = tmp, mapping = aes(x = longitude, y = latitude, 
                                         color = area), size = 3) +
    ggtitle(
      paste("BC Region: ", MyRegion, " with ", NumPoints, 
            " locations in ", NumAreas, " area(s)", sep = "")
      )

ggsave(paste("bc_region", MyRegion, ".pdf", sep = ""), the_map, 
       width = 9, height = 9)
}

dump <- lapply(unique(bc$region), region_plot)
```

